;Pour test
[env:micro]
platform = atmelavr
board = micro
framework = arduino
monitor_speed = 115200

; [env:esp32dev]
; platform = espressif32
; board = esp32dev
; framework = arduino
; monitor_speed = 115200

; Ne pas committer le dossier .pio (binaires, cache)
; Ajoute un .gitignore avec : .pio/